=== NacheGod/ertheia/dist/gameserver/data/l2on_npc/l2on_npc.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT list (npc)*>
<!ELEMENT npc (set|action)*>
<!ATTLIST npc
	id CDATA #REQUIRED
	name CDATA #REQUIRED>
<!ELEMENT set (#PCDATA)>
<!ATTLIST set
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT location (map)*>
<!ELEMENT similar (npc)*>
<!ATTLIST map
	x CDATA #IMPLIED
	y CDATA #IMPLIED
	zone CDATA #IMPLIED>

=== NacheGod/ertheia/dist/gameserver/data/l2on_npc/20400-20499.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE list SYSTEM "l2on_npc.dtd">
<list>
  <npc id="20400">
    <set name="Features" value="" />
    <set name="Level" value="12" />
    <set name="HP" value="199" />
    <set name="SP" value="16" />
    <set name="Race" value="plants" />
    <set name="Location" value="" />
    <set name="Exp" value="641" />
  </npc>
  <npc id="20401">
    <set name="Features" value="" />
    <set name="Level" value="23" />
    <set name="HP" value="410" />
    <set name="SP" value="50" />
    <set name="Race" value="giants" />
    <set name="Location" value="" />
    <set name="Exp" value="1581" />
  </npc>
  <npc id="20402">
    <set name="Quest" value="" />
    <set name="Features" value="" />
    <set name="Level" value="34" />
    <set name="HP" value="1168" />
    <set name="SP" value="1" />
    <set name="Herbs" value="yes" />
    <set name="Race" value="giants" />
    <set name="Location" value="" />
    <set name="Exp" value="3446" />
  </npc>
  <npc id="20403">
    <set name="Features" value="" />
    <set name="Level" value="16" />
    <set name="HP" value="418" />
    <set name="SP" value="23" />
    <set name="Herbs" value="yes" />
    <set name="Race" value="bugs" />
    <set name="Location" value="" />
    <set name="Exp" value="856" />
  </npc>
  <npc id="20404">
    <set name="Features" value="" />
    <set name="Level" value="16" />
    <set name="HP" value="264" />
    <set name="SP" value="20" />
    <set name="Race" value="undead" />
    <set name="Location" value="" />
    <set name="Exp" value="727" />
  </npc>
  <npc id="20405">
    <set name="Features" value="" />
    <set name="Level" value="1" />
    <set name="HP" value="39" />
    <set name="SP" value="2" />
    <set name="Race" value="animals" />
    <set name="Exp" value="44" />
  </npc>
  <npc id="20406">
    <set name="Features" value="" />
    <set name="Level" value="1" />
    <set name="HP" value="39" />
    <set name="SP" value="2" />
    <set name="Race" value="animals" />
    <set name="Exp" value="44" />
  </npc>
  <npc id="20407">
    <set name="Features" value="" />
    <set name="Level" value="1" />
    <set name="HP" value="39" />
    <set name="SP" value="2" />
    <set name="Race" value="animals" />
    <set name="Exp" value="44" />
  </npc>
  <npc id="20410">
    <set name="Features" value="" />
    <set name="Level" value="15" />
    <set name="HP" value="391" />
    <set name="SP" value="22" />
    <set name="Herbs" value="yes" />
    <set name="Race" value="bugs" />
    <set name="Location" value="" />
    <set name="Exp" value="817" />
  </npc>
  <npc id="20411">
    <set name="Quest" value="" />
    <set name="Features" value="" />
    <set name="Level" value="30" />
    <set name="HP" value="957" />
    <set name="SP" value="1" />
    <set name="Herbs" value="yes" />
    <set name="Race" value="animals" />
    <set name="Location" value="" />
    <set name="Exp" value="2667" />
  </npc>
  <npc id="20412">
    <set name="Features" value="" />
    <set name="Level" value="49" />
    <set name="HP" value="1372" />
    <set name="SP" value="1" />
    <set name="Race" value="magic creatures" />
    <set name="Exp" value="5238" />
    <set name="Similar" value="" />
  </npc>
  <npc id="20415">
    <set name="Features" value="" />
    <set name="Level" value="17" />
    <set name="HP" value="282" />
    <set name="SP" value="23" />
    <set name="Race" value="spirits" />
    <set name="Location" value="" />
    <set name="Exp" value="833" />
  </npc>
  <npc id="20416">
    <set name="Features" value="" />
    <set name="Level" value="18" />
    <set name="HP" value="301" />
    <set name="SP" value="26" />
    <set name="Race" value="spirits" />
    <set name="Location" value="" />
    <set name="Exp" value="880" />
  </npc>
  <npc id="20418">
    <set name="Features" value="" />
    <set name="Level" value="18" />
    <set name="HP" value="301" />
    <set name="SP" value="28" />
    <set name="Race" value="beasts" />
    <set name="Location" value="" />
    <set name="Exp" value="950" />
  </npc>
  <npc id="20419">
    <set name="Features" value="" />
    <set name="Level" value="20" />
    <set name="HP" value="342" />
    <set name="SP" value="27" />
    <set name="Race" value="demons" />
    <set name="Exp" value="908" />
  </npc>
  <npc id="20420">
    <set name="Features" value="" />
    <set name="Level" value="21" />
    <set name="HP" value="364" />
    <set name="SP" value="36" />
    <set name="Race" value="demons" />
    <set name="Location" value="" />
    <set name="Exp" value="1169" />
  </npc>
  <npc id="20421">
    <set name="Features" value="" />
    <set name="Level" value="22" />
    <set name="HP" value="387" />
    <set name="SP" value="40" />
    <set name="Race" value="demons" />
    <set name="Location" value="" />
    <set name="Exp" value="1256" />
  </npc>
  <npc id="20422">
    <set name="Features" value="" />
    <set name="Level" value="17" />
    <set name="HP" value="282" />
    <set name="SP" value="26" />
    <set name="Race" value="undead" />
    <set name="Location" value="" />
    <set name="Exp" value="919" />
  </npc>
  <npc id="20423">
    <set name="Features" value="" />
    <set name="Level" value="14" />
    <set name="HP" value="365" />
    <set name="SP" value="17" />
    <set name="Race" value="undead" />
    <set name="Location" value="" />
    <set name="Exp" value="642" />
  </npc>
  <npc id="20424">
    <set name="Features" value="" />
    <set name="Level" value="19" />
    <set name="HP" value="321" />
    <set name="SP" value="26" />
    <set name="Race" value="undead" />
    <set name="Location" value="" />
    <set name="Exp" value="888" />
  </npc>
  <npc id="20425">
    <set name="Features" value="" />
    <set name="Level" value="12" />
    <set name="HP" value="316" />
    <set name="SP" value="13" />
    <set name="Herbs" value="no" />
    <set name="Race" value="undead" />
    <set name="Location" value="" />
    <set name="Exp" value="545" />
  </npc>
  <npc id="20426">
    <set name="Features" value="" />
    <set name="Level" value="10" />
    <set name="HP" value="163" />
    <set name="SP" value="12" />
    <set name="Herbs" value="yes" />
    <set name="Race" value="magic creatures" />
    <set name="Location" value="" />
    <set name="Exp" value="534" />
  </npc>
  <npc id="20427">
    <set name="Features" value="" />
    <set name="Level" value="10" />
    <set name="HP" value="163" />
    <set name="SP" value="10" />
    <set name="Race" value="magic creatures" />
    <set name="Location" value="" />
    <set name="Exp" value="445" />
  </npc>
  <npc id="20428">
    <set name="Features" value="" />
    <set name="Level" value="14" />
    <set name="HP" value="230" />
    <set name="SP" value="19" />
    <set name="Herbs" value="yes" />
    <set name="Race" value="magic creatures" />
    <set name="Location" value="" />
    <set name="Exp" value="748" />
  </npc>
  <npc id="20429">
    <set name="Features" value="" />
    <set name="Level" value="14" />
    <set name="HP" value="230" />
    <set name="SP" value="16" />
    <set name="Race" value="magic creatures" />
    <set name="Location" value="" />
    <set name="Exp" value="623" />
  </npc>
  <npc id="20431">
    <set name="Features" value="" />
    <set name="Level" value="20" />
    <set name="HP" value="342" />
    <set name="SP" value="27" />
    <set name="Race" value="undead" />
    <set name="Exp" value="908" />
  </npc>
  <npc id="20432">
    <set name="Features" value="" />
    <set name="Level" value="1" />
    <set name="HP" value="39" />
    <set name="SP" value="2" />
    <set name="Race" value="animals" />
    <set name="Location" value="" />
    <set name="Exp" value="52" />
  </npc>
  <npc id="20433">
    <set name="Features" value="" />
    <set name="Level" value="13" />
    <set name="HP" value="214" />
    <set name="SP" value="18" />
    <set name="Race" value="animals" />
    <set name="Location" value="" />
    <set name="Exp" value="694" />
  </npc>
  <npc id="20435">
    <set name="Features" value="" />
    <set name="Level" value="15" />
    <set name="HP" value="391" />
    <set name="SP" value="18" />
    <set name="Race" value="beasts" />
    <set name="Location" value="" />
    <set name="Exp" value="674" />
  </npc>
  <npc id="20436">
    <set name="Features" value="" />
    <set name="Level" value="23" />
    <set name="HP" value="410" />
    <set name="SP" value="50" />
    <set name="Race" value="humanoids" />
    <set name="Location" value="" />
    <set name="Exp" value="1581" />
  </npc>
  <npc id="20437">
    <set name="Features" value="" />
    <set name="Level" value="21" />
    <set name="HP" value="364" />
    <set name="SP" value="42" />
    <set name="Race" value="humanoids" />
    <set name="Location" value="" />
    <set name="Exp" value="1375" />
  </npc>
  <npc id="20438">
    <set name="Features" value="" />
    <set name="Level" value="26" />
    <set name="HP" value="487" />
    <set name="SP" value="65" />
    <set name="Race" value="humanoids" />
    <set name="Location" value="" />
    <set name="Exp" value="1940" />
  </npc>
  <npc id="20439">
    <set name="Features" value="" />
    <set name="Level" value="24" />
    <set name="HP" value="435" />
    <set name="SP" value="55" />
    <set name="Herbs" value="yes" />
    <set name="Race" value="humanoids" />
    <set name="Location" value="" />
    <set name="Exp" value="1683" />
  </npc>
  <npc id="20440">
    <set name="Features" value="" />
    <set name="Level" value="3" />
    <set name="HP" value="57" />
    <set name="SP" value="2" />
    <set name="Race" value="animals" />
    <set name="Exp" value="132" />
  </npc>
  <npc id="20441">
    <set name="Features" value="" />
    <set name="Level" value="3" />
    <set name="HP" value="57" />
    <set name="SP" value="2" />
    <set name="Race" value="animals" />
    <set name="Exp" value="132" />
