=== NacheGod/ertheia/dist/gameserver/data/skill_tree/tree.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT list (sub_unit_skill_tree|pledge_skill_tree|collection_skill_tree|certification_skill_tree|dual_certification_skill_tree|transfer_skill_tree|normal_skill_tree|chaos_skill_tree|dual_chaos_skill_tree|dual_class_skill_tree|fishing_skill_tree|transformation_skill_tree|awake_parent_skill_tree|noblesse_skill_tree|hero_skill_tree|gm_skill_tree|forgotten_book_skill_tree|ability_skill_tree|abilities_settings|alchemy_skill_tree)*>
<!ELEMENT transfer_skill_tree (class)*>
<!ELEMENT normal_skill_tree (class)*>
<!ELEMENT dual_class_skill_tree (class)*>
<!ELEMENT awake_parent_skill_tree (awake_class)*>
<!ELEMENT sub_unit_skill_tree (skill)*>
<!ELEMENT pledge_skill_tree (skill)*>
<!ELEMENT collection_skill_tree (skill)*>
<!ELEMENT certification_skill_tree (skill)*>
<!ELEMENT dual_certification_skill_tree (skill)*>
<!ELEMENT fishing_skill_tree (skill)*>
<!ELEMENT transformation_skill_tree (skill)*>
<!ELEMENT chaos_skill_tree (skill)*>
<!ELEMENT dual_chaos_skill_tree (skill)*>
<!ELEMENT noblesse_skill_tree (skill)*>
<!ELEMENT hero_skill_tree (skill)*>
<!ELEMENT gm_skill_tree (skill)*>
<!ELEMENT forgotten_book_skill_tree (skill|class)*>
<!ELEMENT ability_skill_tree (skill)*>
<!ELEMENT alchemy_skill_tree (skill)*>
	<!ELEMENT skill (#PCDATA)>
		<!ATTLIST skill
			id CDATA #REQUIRED
			item_count CDATA #IMPLIED
			item_id CDATA #IMPLIED
			level CDATA #REQUIRED
			min_level CDATA #IMPLIED
			name CDATA #IMPLIED
			cost CDATA #IMPLIED
			race CDATA #IMPLIED
			auto_get CDATA #IMPLIED
			dual_class_min_level CDATA #IMPLIED>
	<!ELEMENT class (skill)*>
		<!ATTLIST class id CDATA #REQUIRED>
	<!ELEMENT awake_class (parent_class)*>
		<!ATTLIST awake_class id CDATA #REQUIRED>
		<!ELEMENT parent_class (skill)*>
			<!ATTLIST parent_class id CDATA #REQUIRED>

<!ELEMENT abilities_settings (point)*>
	<!ATTLIST abilities_settings
		maximun_points CDATA #REQUIRED
		refresh_price CDATA #REQUIRED>
	<!ELEMENT point (#PCDATA)>
		<!ATTLIST point
			ordinal CDATA #REQUIRED
			sp_cost CDATA #REQUIRED>

=== NacheGod/ertheia/dist/gameserver/data/skill_tree/normal_skill_tree/[42] shillien_oracle.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "tree.dtd">
<!--Create by VISTALL. Full reworked to Glory of Destruction by Bonux. -->
<list>
	<normal_skill_tree>
		<class id="42"> <!--shillien_oracle-->
			<skill id="146" level="5" cost="160" name="Anti Magic" min_level="20"/>
			<skill id="146" level="6" cost="160" name="Anti Magic" min_level="20"/>
			<skill id="146" level="7" cost="320" name="Anti Magic" min_level="25"/>
			<skill id="146" level="8" cost="320" name="Anti Magic" min_level="25"/>
			<skill id="146" level="9" cost="580" name="Anti Magic" min_level="30"/>
			<skill id="146" level="10" cost="580" name="Anti Magic" min_level="30"/>
			<skill id="146" level="11" cost="1200" name="Anti Magic" min_level="35"/>
			<skill id="146" level="12" cost="1200" name="Anti Magic" min_level="35"/>
			<skill id="164" level="1" cost="330" name="Quick Recycle" min_level="20"/>
			<skill id="164" level="2" cost="1200" name="Quick Recycle" min_level="30"/>
			<skill id="212" level="1" cost="2300" name="Fast HP Recovery" min_level="35"/>
			<skill id="213" level="1" cost="330" name="Boost Mana" min_level="20"/>
			<skill id="213" level="2" cost="1200" name="Boost Mana" min_level="30"/>
			<skill id="228" level="1" cost="650" name="Fast Spell Casting" min_level="25"/>
			<skill id="229" level="1" cost="650" name="Fast Mana Recovery" min_level="25"/>
			<skill id="229" level="2" cost="2300" name="Fast Mana Recovery" min_level="35"/>
			<skill id="235" level="1" cost="160" name="Robe Mastery" min_level="20"/>
			<skill id="235" level="2" cost="160" name="Robe Mastery" min_level="20"/>
			<skill id="235" level="3" cost="320" name="Robe Mastery" min_level="25"/>
			<skill id="235" level="4" cost="320" name="Robe Mastery" min_level="25"/>
			<skill id="235" level="5" cost="580" name="Robe Mastery" min_level="30"/>
			<skill id="235" level="6" cost="580" name="Robe Mastery" min_level="30"/>
			<skill id="235" level="7" cost="1200" name="Robe Mastery" min_level="35"/>
			<skill id="235" level="8" cost="1200" name="Robe Mastery" min_level="35"/>
			<skill id="236" level="1" cost="160" name="Light Armor Mastery" min_level="20"/>
			<skill id="236" level="2" cost="160" name="Light Armor Mastery" min_level="20"/>
			<skill id="236" level="3" cost="320" name="Light Armor Mastery" min_level="25"/>
			<skill id="236" level="4" cost="320" name="Light Armor Mastery" min_level="25"/>
			<skill id="236" level="5" cost="580" name="Light Armor Mastery" min_level="30"/>
			<skill id="236" level="6" cost="580" name="Light Armor Mastery" min_level="30"/>
			<skill id="236" level="7" cost="1200" name="Light Armor Mastery" min_level="35"/>
			<skill id="236" level="8" cost="1200" name="Light Armor Mastery" min_level="35"/>
			<skill id="249" level="3" cost="330" name="Weapon Mastery" min_level="20"/>
			<skill id="249" level="4" cost="320" name="Weapon Mastery" min_level="25"/>
			<skill id="249" level="5" cost="320" name="Weapon Mastery" min_level="25"/>
			<skill id="249" level="6" cost="580" name="Weapon Mastery" min_level="30"/>
			<skill id="249" level="7" cost="580" name="Weapon Mastery" min_level="30"/>
			<skill id="249" level="8" cost="1200" name="Weapon Mastery" min_level="35"/>
			<skill id="249" level="9" cost="1200" name="Weapon Mastery" min_level="35"/>
			<skill id="1011" level="7" cost="110" name="Heal" min_level="20"/>
			<skill id="1011" level="8" cost="110" name="Heal" min_level="20"/>
			<skill id="1011" level="9" cost="110" name="Heal" min_level="20"/>
			<skill id="1011" level="10" cost="220" name="Heal" min_level="25"/>
			<skill id="1011" level="11" cost="220" name="Heal" min_level="25"/>
			<skill id="1011" level="12" cost="220" name="Heal" min_level="25"/>
			<skill id="1011" level="13" cost="390" name="Heal" min_level="30"/>
			<skill id="1011" level="14" cost="390" name="Heal" min_level="30"/>
			<skill id="1011" level="15" cost="390" name="Heal" min_level="30"/>
			<skill id="1011" level="16" cost="770" name="Heal" min_level="35"/>
			<skill id="1011" level="17" cost="770" name="Heal" min_level="35"/>
			<skill id="1011" level="18" cost="770" name="Heal" min_level="35"/>
			<skill id="1012" level="2" cost="2300" name="Cure Poison" min_level="35"/>
			<skill id="1013" level="1" cost="580" name="Recharge" min_level="30"/>
			<skill id="1013" level="2" cost="580" name="Recharge" min_level="30"/>
			<skill id="1013" level="3" cost="1200" name="Recharge" min_level="35"/>
			<skill id="1013" level="4" cost="1200" name="Recharge" min_level="35"/>
			<skill id="1015" level="4" cost="110" name="Battle Heal" min_level="20"/>
			<skill id="1015" level="5" cost="110" name="Battle Heal" min_level="20"/>
			<skill id="1015" level="6" cost="110" name="Battle Heal" min_level="20"/>
			<skill id="1015" level="7" cost="220" name="Battle Heal" min_level="25"/>
			<skill id="1015" level="8" cost="220" name="Battle Heal" min_level="25"/>
			<skill id="1015" level="9" cost="220" name="Battle Heal" min_level="25"/>
			<skill id="1015" level="10" cost="390" name="Battle Heal" min_level="30"/>
			<skill id="1015" level="11" cost="390" name="Battle Heal" min_level="30"/>
			<skill id="1015" level="12" cost="390" name="Battle Heal" min_level="30"/>
			<skill id="1015" level="13" cost="770" name="Battle Heal" min_level="35"/>
			<skill id="1015" level="14" cost="770" name="Battle Heal" min_level="35"/>
			<skill id="1015" level="15" cost="770" name="Battle Heal" min_level="35"/>
			<skill id="1016" level="1" cost="330" name="Resurrection" min_level="20"/>
			<skill id="1016" level="2" cost="1200" name="Resurrection" min_level="30"/>
			<skill id="1027" level="4" cost="110" name="Group Heal" min_level="20"/>
			<skill id="1027" level="5" cost="110" name="Group Heal" min_level="20"/>
			<skill id="1027" level="6" cost="110" name="Group Heal" min_level="20"/>
			<skill id="1027" level="7" cost="220" name="Group Heal" min_level="25"/>
			<skill id="1027" level="8" cost="220" name="Group Heal" min_level="25"/>
			<skill id="1027" level="9" cost="220" name="Group Heal" min_level="25"/>
			<skill id="1027" level="10" cost="390" name="Group Heal" min_level="30"/>
			<skill id="1027" level="11" cost="390" name="Group Heal" min_level="30"/>
			<skill id="1027" level="12" cost="390" name="Group Heal" min_level="30"/>
			<skill id="1027" level="13" cost="770" name="Group Heal" min_level="35"/>
			<skill id="1027" level="14" cost="770" name="Group Heal" min_level="35"/>
			<skill id="1027" level="15" cost="770" name="Group Heal" min_level="35"/>
			<skill id="1031" level="1" cost="160" name="Disrupt Undead" min_level="20"/>
			<skill id="1031" level="2" cost="160" name="Disrupt Undead" min_level="20"/>
			<skill id="1031" level="3" cost="320" name="Disrupt Undead" min_level="25"/>
			<skill id="1031" level="4" cost="320" name="Disrupt Undead" min_level="25"/>
			<skill id="1031" level="5" cost="580" name="Disrupt Undead" min_level="30"/>
			<skill id="1031" level="6" cost="580" name="Disrupt Undead" min_level="30"/>
			<skill id="1031" level="7" cost="1200" name="Disrupt Undead" min_level="35"/>
			<skill id="1031" level="8" cost="1200" name="Disrupt Undead" min_level="35"/>
			<skill id="1035" level="1" cost="650" name="Mental Shield" min_level="25"/>
			<skill id="1040" level="2" cost="650" name="Shield" min_level="25"/>
			<skill id="1059" level="1" cost="650" name="Empower" min_level="25"/>
			<skill id="1068" level="2" cost="330" name="Might" min_level="20"/>
			<skill id="1069" level="1" cost="220" name="Sleep" min_level="25"/>
			<skill id="1069" level="2" cost="220" name="Sleep" min_level="25"/>
			<skill id="1069" level="3" cost="220" name="Sleep" min_level="25"/>
			<skill id="1069" level="4" cost="390" name="Sleep" min_level="30"/>
			<skill id="1069" level="5" cost="390" name="Sleep" min_level="30"/>
			<skill id="1069" level="6" cost="390" name="Sleep" min_level="30"/>
			<skill id="1069" level="7" cost="770" name="Sleep" min_level="35"/>
			<skill id="1069" level="8" cost="770" name="Sleep" min_level="35"/>
			<skill id="1069" level="9" cost="770" name="Sleep" min_level="35"/>
			<skill id="1073" level="1" cost="330" name="Kiss of Eva" min_level="20"/>
			<skill id="1077" level="1" cost="650" name="Focus" min_level="25"/>
			<skill id="1078" level="1" cost="330" name="Concentration" min_level="20"/>
			<skill id="1078" level="2" cost="1200" name="Concentration" min_level="30"/>
			<skill id="1189" level="1" cost="2300" name="Resist Wind" min_level="35"/>
			<skill id="1201" level="1" cost="220" name="Dryad Root" min_level="25"/>
			<skill id="1201" level="2" cost="220" name="Dryad Root" min_level="25"/>
			<skill id="1201" level="3" cost="220" name="Dryad Root" min_level="25"/>
			<skill id="1201" level="4" cost="390" name="Dryad Root" min_level="30"/>
			<skill id="1201" level="5" cost="390" name="Dryad Root" min_level="30"/>
			<skill id="1201" level="6" cost="390" name="Dryad Root" min_level="30"/>
			<skill id="1201" level="7" cost="770" name="Dryad Root" min_level="35"/>
			<skill id="1201" level="8" cost="770" name="Dryad Root" min_level="35"/>
			<skill id="1201" level="9" cost="770" name="Dryad Root" min_level="35"/>
			<skill id="1204" level="1" cost="330" name="Wind Walk" min_level="20"/>
			<skill id="1204" level="2" cost="1200" name="Wind Walk" min_level="30"/>
			<skill id="1206" level="2" cost="330" name="Wind Shackle" min_level="20"/>
			<skill id="1206" level="3" cost="650" name="Wind Shackle" min_level="25"/>
			<skill id="1206" level="4" cost="1200" name="Wind Shackle" min_level="30"/>
			<skill id="1206" level="5" cost="2300" name="Wind Shackle" min_level="35"/>
			<skill id="1268" level="1" cost="1200" name="Vampiric Rage" min_level="30"/>
		</class>
	</normal_skill_tree>
</list>

=== NacheGod/ertheia/dist/gameserver/data/skill_tree/awake_parent_skill_tree/[161] othell_fortune_seeker.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "tree.dtd">
<!--Create by VISTALL. Full reworked to Glory of Destruction by Bonux. -->
<list>
	<awake_parent_skill_tree>
		<awake_class id="161">	<!--Разбойник Одала-->
			<parent_class id="117"> <!--Кладоискатель-->
				<skill id="30" level="37" name="Backstab"/>
				<skill id="36" level="37" name="Spinning Slasher"/>
				<skill id="60" level="1" name="Fake Death"/>
				<skill id="148" level="8" name="Vital Force"/>
				<skill id="190" level="37" name="Fatal Strike"/>
				<skill id="205" level="45" name="Sword/Blunt Weapon Mastery"/>
				<skill id="209" level="45" name="Dagger Mastery"/>
				<skill id="211" level="10" name="Boost HP"/>
				<skill id="212" level="8" name="Fast HP Recovery"/>
				<skill id="216" level="45" name="Polearm Mastery"/>
				<skill id="227" level="50" name="Light Armor Mastery"/>
				<skill id="231" level="50" name="Heavy Armor Mastery"/>
				<skill id="260" level="37" name="Hammer Crush"/>
				<skill id="263" level="37" name="Deadly Blow"/>
				<skill id="328" level="1" name="Wisdom"/>
				<skill id="329" level="1" name="Health"/>
				<skill id="330" level="1" name="Skill Mastery"/>
				<skill id="347" level="1" name="Earthquake"/>
				<skill id="422" level="3" name="Polearm Accuracy"/>
				<skill id="952" level="5" name="Collector's Experience"/>
				<skill id="997" level="25" name="Crushing Strike"/>
				<skill id="998" level="1" name="Blazing Boost"/>
				<skill id="1559" level="3" name="Potential Ability"/>
			</parent_class>
		</awake_class>
	</awake_parent_skill_tree>
</list>

=== NacheGod/ertheia/dist/gameserver/data/skill_tree/normal_skill_tree/[1] warrior.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "tree.dtd">
<!--Create by VISTALL. Full reworked to Glory of Destruction by Bonux. -->
<list>
	<normal_skill_tree>
		<class id="1"> <!--warrior-->
			<skill id="312" level="1" cost="370" name="Vicious Stance" min_level="20"/>
			<skill id="216" level="1" cost="370" name="Polearm Mastery" min_level="20"/>
			<skill id="227" level="1" cost="190" name="Light Armor Mastery" min_level="20"/>
			<skill id="227" level="2" cost="190" name="Light Armor Mastery" min_level="20"/>
			<skill id="257" level="1" cost="370" name="Sword/Blunt Weapon Mastery" min_level="20"/>
			<skill id="231" level="1" cost="190" name="Heavy Armor Mastery" min_level="20"/>
			<skill id="231" level="2" cost="190" name="Heavy Armor Mastery" min_level="20"/>
			<skill id="245" level="1" cost="120" name="Wild Sweep" min_level="20"/>
			<skill id="245" level="2" cost="120" name="Wild Sweep" min_level="20"/>
			<skill id="245" level="3" cost="120" name="Wild Sweep" min_level="20"/>
			<skill id="78" level="1" cost="370" name="War Cry" min_level="20"/>
			<skill id="255" level="1" cost="120" name="Power Smash" min_level="20"/>
			<skill id="255" level="2" cost="120" name="Power Smash" min_level="20"/>
			<skill id="255" level="3" cost="120" name="Power Smash" min_level="20"/>
			<skill id="100" level="1" cost="120" name="Stun Attack" min_level="20"/>
			<skill id="100" level="2" cost="120" name="Stun Attack" min_level="20"/>
			<skill id="100" level="3" cost="120" name="Stun Attack" min_level="20"/>
			<skill id="211" level="1" cost="370" name="Boost HP" min_level="20"/>
			<skill id="312" level="2" cost="640" name="Vicious Stance" min_level="24"/>
			<skill id="212" level="1" cost="640" name="Fast HP Recovery" min_level="24"/>
			<skill id="216" level="2" cost="640" name="Polearm Mastery" min_level="24"/>
			<skill id="227" level="3" cost="320" name="Light Armor Mastery" min_level="24"/>
			<skill id="227" level="4" cost="320" name="Light Armor Mastery" min_level="24"/>
			<skill id="257" level="2" cost="640" name="Sword/Blunt Weapon Mastery" min_level="24"/>
			<skill id="231" level="3" cost="320" name="Heavy Armor Mastery" min_level="24"/>
			<skill id="231" level="4" cost="320" name="Heavy Armor Mastery" min_level="24"/>
			<skill id="245" level="4" cost="210" name="Wild Sweep" min_level="24"/>
			<skill id="245" level="5" cost="210" name="Wild Sweep" min_level="24"/>
			<skill id="245" level="6" cost="210" name="Wild Sweep" min_level="24"/>
			<skill id="148" level="1" cost="640" name="Vital Force" min_level="24"/>
			<skill id="255" level="4" cost="210" name="Power Smash" min_level="24"/>
			<skill id="255" level="5" cost="210" name="Power Smash" min_level="24"/>
			<skill id="255" level="6" cost="210" name="Power Smash" min_level="24"/>
			<skill id="100" level="4" cost="210" name="Stun Attack" min_level="24"/>
			<skill id="100" level="5" cost="210" name="Stun Attack" min_level="24"/>
			<skill id="100" level="6" cost="210" name="Stun Attack" min_level="24"/>
			<skill id="256" level="1" cost="640" name="Accuracy" min_level="24"/>
			<skill id="312" level="3" cost="1200" name="Vicious Stance" min_level="28"/>
			<skill id="121" level="1" cost="1200" name="Battle Roar" min_level="28"/>
			<skill id="216" level="3" cost="600" name="Polearm Mastery" min_level="28"/>
			<skill id="216" level="4" cost="600" name="Polearm Mastery" min_level="28"/>
			<skill id="227" level="5" cost="400" name="Light Armor Mastery" min_level="28"/>
			<skill id="227" level="6" cost="400" name="Light Armor Mastery" min_level="28"/>
			<skill id="227" level="7" cost="400" name="Light Armor Mastery" min_level="28"/>
			<skill id="257" level="3" cost="600" name="Sword/Blunt Weapon Mastery" min_level="28"/>
			<skill id="257" level="4" cost="600" name="Sword/Blunt Weapon Mastery" min_level="28"/>
			<skill id="231" level="5" cost="400" name="Heavy Armor Mastery" min_level="28"/>
			<skill id="231" level="6" cost="400" name="Heavy Armor Mastery" min_level="28"/>
			<skill id="231" level="7" cost="400" name="Heavy Armor Mastery" min_level="28"/>
			<skill id="245" level="7" cost="400" name="Wild Sweep" min_level="28"/>
			<skill id="245" level="8" cost="400" name="Wild Sweep" min_level="28"/>
			<skill id="245" level="9" cost="400" name="Wild Sweep" min_level="28"/>
			<skill id="255" level="7" cost="400" name="Power Smash" min_level="28"/>
			<skill id="255" level="8" cost="400" name="Power Smash" min_level="28"/>
			<skill id="255" level="9" cost="400" name="Power Smash" min_level="28"/>
			<skill id="100" level="7" cost="400" name="Stun Attack" min_level="28"/>
			<skill id="100" level="8" cost="400" name="Stun Attack" min_level="28"/>
			<skill id="100" level="9" cost="400" name="Stun Attack" min_level="28"/>
			<skill id="211" level="2" cost="1200" name="Boost HP" min_level="28"/>
			<skill id="312" level="4" cost="1800" name="Vicious Stance" min_level="32"/>
			<skill id="212" level="2" cost="1800" name="Fast HP Recovery" min_level="32"/>
			<skill id="216" level="5" cost="910" name="Polearm Mastery" min_level="32"/>
			<skill id="216" level="6" cost="910" name="Polearm Mastery" min_level="32"/>
			<skill id="227" level="8" cost="610" name="Light Armor Mastery" min_level="32"/>
			<skill id="227" level="9" cost="610" name="Light Armor Mastery" min_level="32"/>
			<skill id="227" level="10" cost="610" name="Light Armor Mastery" min_level="32"/>
			<skill id="257" level="5" cost="910" name="Sword/Blunt Weapon Mastery" min_level="32"/>
			<skill id="257" level="6" cost="910" name="Sword/Blunt Weapon Mastery" min_level="32"/>
			<skill id="231" level="8" cost="610" name="Heavy Armor Mastery" min_level="32"/>
			<skill id="231" level="9" cost="610" name="Heavy Armor Mastery" min_level="32"/>
			<skill id="231" level="10" cost="610" name="Heavy Armor Mastery" min_level="32"/>
			<skill id="245" level="10" cost="610" name="Wild Sweep" min_level="32"/>
			<skill id="245" level="11" cost="610" name="Wild Sweep" min_level="32"/>
			<skill id="245" level="12" cost="610" name="Wild Sweep" min_level="32"/>
			<skill id="148" level="2" cost="1800" name="Vital Force" min_level="32"/>
			<skill id="255" level="10" cost="610" name="Power Smash" min_level="32"/>
			<skill id="255" level="11" cost="610" name="Power Smash" min_level="32"/>
			<skill id="255" level="12" cost="610" name="Power Smash" min_level="32"/>
			<skill id="75" level="1" cost="1800" name="Detect Insect Weakness" min_level="32"/>
			<skill id="100" level="10" cost="610" name="Stun Attack" min_level="32"/>
			<skill id="100" level="11" cost="610" name="Stun Attack" min_level="32"/>
			<skill id="100" level="12" cost="610" name="Stun Attack" min_level="32"/>
			<skill id="312" level="5" cost="3100" name="Vicious Stance" min_level="36"/>
			<skill id="216" level="7" cost="1600" name="Polearm Mastery" min_level="36"/>
			<skill id="216" level="8" cost="1600" name="Polearm Mastery" min_level="36"/>
			<skill id="227" level="11" cost="1000" name="Light Armor Mastery" min_level="36"/>
			<skill id="227" level="12" cost="1000" name="Light Armor Mastery" min_level="36"/>
			<skill id="227" level="13" cost="1000" name="Light Armor Mastery" min_level="36"/>
			<skill id="257" level="7" cost="1600" name="Sword/Blunt Weapon Mastery" min_level="36"/>
			<skill id="257" level="8" cost="1600" name="Sword/Blunt Weapon Mastery" min_level="36"/>
			<skill id="231" level="11" cost="1000" name="Heavy Armor Mastery" min_level="36"/>
			<skill id="231" level="12" cost="1000" name="Heavy Armor Mastery" min_level="36"/>
			<skill id="231" level="13" cost="1000" name="Heavy Armor Mastery" min_level="36"/>
			<skill id="245" level="13" cost="1000" name="Wild Sweep" min_level="36"/>
			<skill id="245" level="14" cost="1000" name="Wild Sweep" min_level="36"/>
			<skill id="245" level="15" cost="1000" name="Wild Sweep" min_level="36"/>
			<skill id="287" level="1" cost="3100" name="Lionheart" min_level="36"/>
			<skill id="255" level="13" cost="1000" name="Power Smash" min_level="36"/>
			<skill id="255" level="14" cost="1000" name="Power Smash" min_level="36"/>
			<skill id="255" level="15" cost="1000" name="Power Smash" min_level="36"/>
			<skill id="100" level="13" cost="1000" name="Stun Attack" min_level="36"/>
			<skill id="100" level="14" cost="1000" name="Stun Attack" min_level="36"/>
			<skill id="100" level="15" cost="1000" name="Stun Attack" min_level="36"/>
			<skill id="211" level="3" cost="3100" name="Boost HP" min_level="36"/>
		</class>
	</normal_skill_tree>
</list>

=== NacheGod/ertheia/dist/gameserver/data/skill_tree/awake_parent_skill_tree/[179] eolh_cardinal.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "tree.dtd">
<!--Create by VISTALL. Full reworked to Glory of Destruction by Bonux. -->
<list>
	<awake_parent_skill_tree>
		<awake_class id="179">	<!--Целитель Альгиза-->
			<parent_class id="97"> <!--Кардинал-->		
				<skill id="146" level="45" name="Anti Magic"/>
				<skill id="164" level="3" name="Quick Recovery"/>
				<skill id="212" level="6" name="Fast HP Recovery"/>
				<skill id="213" level="8" name="Boost Mana"/>
				<skill id="228" level="3" name="Fast Spell Casting"/>
				<skill id="229" level="7" name="Fast Mana Recovery"/>
				<skill id="235" level="41" name="Robe Mastery"/>
				<skill id="249" level="42" name="Weapon Mastery"/>
				<skill id="328" level="1" name="Wisdom"/>
				<skill id="329" level="1" name="Health"/>
				<skill id="436" level="1" name="Divine Lore"/>
				<skill id="926" level="1" name="Sigil Mastery"/>
				<skill id="1012" level="3" name="Cure Poison"/>
				<skill id="1016" level="9" name="Resurrection"/>
				<skill id="1028" level="19" name="Might of Heaven"/>
				<skill id="1034" level="13" name="Repose"/>
				<skill id="1042" level="12" name="Hold Undead"/>
				<skill id="1069" level="42" name="Sleep"/>
				<skill id="1075" level="15" name="Peace"/>
				<skill id="1217" level="33" name="Greater Heal"/>
				<skill id="1218" level="33" name="Greater Battle Heal"/>
				<skill id="1219" level="33" name="Greater Group Heal"/>
				<skill id="1254" level="6" name="Mass Resurrection"/>
				<skill id="1271" level="1" name="Benediction"/>
				<skill id="1311" level="6" name="Body of Avatar"/>
				<skill id="1335" level="1" name="Balance Life"/>
				<skill id="1353" level="1" name="Holy Attack Resistance"/>
				<skill id="1360" level="1" name="Mass Block Shield"/>
				<skill id="1361" level="1" name="Mass Block Wind Walk"/>
				<skill id="1394" level="10" name="Trance"/>
				<skill id="1395" level="10" name="Erase"/>
				<skill id="1396" level="10" name="Magical Backfire"/>
				<skill id="1401" level="11" name="Major Heal"/>
				<skill id="1402" level="5" name="Major Group Heal"/>
				<skill id="1409" level="1" name="Cleanse"/>
				<skill id="1410" level="1" name="Salvation"/>
				<skill id="1418" level="1" name="Celestial Shield"/>
				<skill id="1430" level="5" name="Invocation"/>
				<skill id="1459" level="1" name="Divine Power"/>
				<skill id="1524" level="13" name="Surrender to Holy"/>
				<skill id="1553" level="1" name="Chain Heal"/>
			</parent_class>
		</awake_class>
	</awake_parent_skill_tree>
</list>

=== NacheGod/ertheia/dist/gameserver/data/skill_tree/normal_skill_tree/[49] orc_mage.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "tree.dtd">
<!--Create by VISTALL. Full reworked to Glory of Destruction by Bonux. -->
<list>
	<normal_skill_tree>
		<class id="49"> <!--orc_mage-->
			<skill id="194" level="1" name="Lucky" min_level="1"/>
			<skill id="214" level="1" name="Mana Recovery" min_level="1"/>
			<skill id="118" level="1" name="Magician's Movement" min_level="1"/>
			<skill id="163" level="1" name="Spellcraft" min_level="1"/>
			<skill id="1001" level="1" name="Soul Cry" min_level="1"/>
			<skill id="1322" level="1" name="Common Craft" min_level="1"/>
			<skill id="134" level="1" name="Toughness" min_level="1"/>
			<skill id="1320" level="1" name="Create Common Item" min_level="5"/>
			<skill id="146" level="1" cost="26" name="Anti Magic" min_level="7"/>
			<skill id="146" level="2" cost="26" name="Anti Magic" min_level="7"/>
			<skill id="252" level="1" cost="26" name="Light Armor Mastery" min_level="7"/>
			<skill id="252" level="2" cost="26" name="Light Armor Mastery" min_level="7"/>
			<skill id="251" level="1" cost="26" name="Robe Mastery" min_level="7"/>
			<skill id="251" level="2" cost="26" name="Robe Mastery" min_level="7"/>
			<skill id="250" level="1" cost="52" name="Weapon Mastery" min_level="7"/>
			<skill id="1090" level="1" cost="52" name="Life Drain" min_level="7"/>
			<skill id="1100" level="1" cost="52" name="Chill Flame" min_level="7"/>
			<skill id="1095" level="1" cost="52" name="Venom" min_level="7"/>
			<skill id="1097" level="1" cost="52" name="Dreaming Spirit" min_level="7"/>
			<skill id="1010" level="1" cost="52" name="Soul Shield" min_level="7"/>
			<skill id="146" level="3" cost="88" name="Anti Magic" min_level="14"/>
			<skill id="146" level="4" cost="88" name="Anti Magic" min_level="14"/>
			<skill id="252" level="3" cost="88" name="Light Armor Mastery" min_level="14"/>
			<skill id="252" level="4" cost="88" name="Light Armor Mastery" min_level="14"/>
			<skill id="251" level="3" cost="88" name="Robe Mastery" min_level="14"/>
			<skill id="251" level="4" cost="88" name="Robe Mastery" min_level="14"/>
			<skill id="250" level="2" cost="180" name="Weapon Mastery" min_level="14"/>
			<skill id="253" level="1" cost="88" name="Heavy Armor Mastery" min_level="14"/>
			<skill id="253" level="2" cost="88" name="Heavy Armor Mastery" min_level="14"/>
			<skill id="1090" level="2" cost="180" name="Life Drain" min_level="14"/>
			<skill id="1001" level="2" cost="180" name="Soul Cry" min_level="14"/>
			<skill id="1007" level="1" cost="180" name="Chant of Battle" min_level="14"/>
			<skill id="1100" level="2" cost="180" name="Chill Flame" min_level="14"/>
			<skill id="1095" level="2" cost="180" name="Venom" min_level="14"/>
			<skill id="1097" level="2" cost="180" name="Dreaming Spirit" min_level="14"/>
			<skill id="1092" level="1" cost="180" name="Fear" min_level="14"/>
			<!--HARDCODED: <skill id="239"level="1" name="Expertise D" min_level="20"/>-->
			<skill id="1320" level="2" name="Create Common Item" min_level="20"/>
			<skill id="1320" level="3" name="Create Common Item" min_level="28"/>
			<skill id="1320" level="4" name="Create Common Item" min_level="36"/>
			<!--HARDCODED: <skill id="239"level="2" name="Expertise C" min_level="40"/>-->
			<skill id="1320" level="5" name="Create Common Item" min_level="43"/>
			<skill id="1320" level="6" name="Create Common Item" min_level="49"/>
			<!--HARDCODED: <skill id="239"level="3" name="Expertise B" min_level="52"/>-->
			<skill id="1320" level="7" name="Create Common Item" min_level="55"/>
			<!--HARDCODED: <skill id="239"level="4" name="Expertise A" min_level="61"/>-->
			<skill id="1320" level="8" name="Create Common Item" min_level="62"/>
			<skill id="1320" level="9" name="Create Common Item" min_level="70"/>
			<!--HARDCODED: <skill id="239"level="5" name="Expertise S" min_level="76"/>-->
			<!--HARDCODED: <skill id="239"level="6" name="Expertise S80" min_level="80"/>-->
			<!--HARDCODED: <skill id="239"level="8" name="Expertise R" min_level="85"/>-->
			<!--HARDCODED: <skill id="239"level="9" name="Expertise R95" min_level="95"/>-->
			<!--HARDCODED: <skill id="239"level="10" name="Expertise R99" min_level="99"/>-->
		</class>
	</normal_skill_tree>
</list>
