=== NacheGod/ertheia/dist/gameserver/data/skill_tree/tree.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT list (sub_unit_skill_tree|pledge_skill_tree|collection_skill_tree|certification_skill_tree|dual_certification_skill_tree|transfer_skill_tree|normal_skill_tree|chaos_skill_tree|dual_chaos_skill_tree|dual_class_skill_tree|fishing_skill_tree|transformation_skill_tree|awake_parent_skill_tree|noblesse_skill_tree|hero_skill_tree|gm_skill_tree|forgotten_book_skill_tree|ability_skill_tree|abilities_settings|alchemy_skill_tree)*>
<!ELEMENT transfer_skill_tree (class)*>
<!ELEMENT normal_skill_tree (class)*>
<!ELEMENT dual_class_skill_tree (class)*>
<!ELEMENT awake_parent_skill_tree (awake_class)*>
<!ELEMENT sub_unit_skill_tree (skill)*>
<!ELEMENT pledge_skill_tree (skill)*>
<!ELEMENT collection_skill_tree (skill)*>
<!ELEMENT certification_skill_tree (skill)*>
<!ELEMENT dual_certification_skill_tree (skill)*>
<!ELEMENT fishing_skill_tree (skill)*>
<!ELEMENT transformation_skill_tree (skill)*>
<!ELEMENT chaos_skill_tree (skill)*>
<!ELEMENT dual_chaos_skill_tree (skill)*>
<!ELEMENT noblesse_skill_tree (skill)*>
<!ELEMENT hero_skill_tree (skill)*>
<!ELEMENT gm_skill_tree (skill)*>
<!ELEMENT forgotten_book_skill_tree (skill|class)*>
<!ELEMENT ability_skill_tree (skill)*>
<!ELEMENT alchemy_skill_tree (skill)*>
	<!ELEMENT skill (#PCDATA)>
		<!ATTLIST skill
			id CDATA #REQUIRED
			item_count CDATA #IMPLIED
			item_id CDATA #IMPLIED
			level CDATA #REQUIRED
			min_level CDATA #IMPLIED
			name CDATA #IMPLIED
			cost CDATA #IMPLIED
			race CDATA #IMPLIED
			auto_get CDATA #IMPLIED
			dual_class_min_level CDATA #IMPLIED>
	<!ELEMENT class (skill)*>
		<!ATTLIST class id CDATA #REQUIRED>
	<!ELEMENT awake_class (parent_class)*>
		<!ATTLIST awake_class id CDATA #REQUIRED>
		<!ELEMENT parent_class (skill)*>
			<!ATTLIST parent_class id CDATA #REQUIRED>

<!ELEMENT abilities_settings (point)*>
	<!ATTLIST abilities_settings
		maximun_points CDATA #REQUIRED
		refresh_price CDATA #REQUIRED>
	<!ELEMENT point (#PCDATA)>
		<!ATTLIST point
			ordinal CDATA #REQUIRED
			sp_cost CDATA #REQUIRED>

=== NacheGod/ertheia/dist/gameserver/data/skill_tree/normal_skill_tree/[31] dark_fighter.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "tree.dtd">
<!--Create by VISTALL. Full reworked to Glory of Destruction by Bonux. -->
<list>
	<normal_skill_tree>
		<class id="31"> <!--dark_fighter-->
			<skill id="194" level="1" name="Lucky" min_level="1"/>
			<skill id="1322" level="1" name="Common Craft" min_level="1"/>
			<skill id="91" level="1" cost="16" name="Defense Aura" min_level="5"/>
			<skill id="142" level="1" cost="16" name="Armor Mastery" min_level="5"/>
			<skill id="141" level="1" cost="16" name="Weapon Mastery" min_level="5"/>
			<skill id="56" level="1" cost="5" name="Power Shot" min_level="5"/>
			<skill id="56" level="2" cost="5" name="Power Shot" min_level="5"/>
			<skill id="56" level="3" cost="5" name="Power Shot" min_level="5"/>
			<skill id="3" level="1" cost="5" name="Power Strike" min_level="5"/>
			<skill id="3" level="2" cost="5" name="Power Strike" min_level="5"/>
			<skill id="3" level="3" cost="5" name="Power Strike" min_level="5"/>
			<skill id="16" level="1" cost="5" name="Mortal Blow" min_level="5"/>
			<skill id="16" level="2" cost="5" name="Mortal Blow" min_level="5"/>
			<skill id="16" level="3" cost="5" name="Mortal Blow" min_level="5"/>
			<skill id="1320" level="1" name="Create Common Item" min_level="5"/>
			<skill id="77" level="1" cost="91" name="Attack Aura" min_level="10"/>
			<skill id="142" level="2" cost="46" name="Armor Mastery" min_level="10"/>
			<skill id="142" level="3" cost="46" name="Armor Mastery" min_level="10"/>
			<skill id="141" level="2" cost="91" name="Weapon Mastery" min_level="10"/>
			<skill id="56" level="4" cost="31" name="Power Shot" min_level="10"/>
			<skill id="56" level="5" cost="31" name="Power Shot" min_level="10"/>
			<skill id="56" level="6" cost="31" name="Power Shot" min_level="10"/>
			<skill id="3" level="4" cost="31" name="Power Strike" min_level="10"/>
			<skill id="3" level="5" cost="31" name="Power Strike" min_level="10"/>
			<skill id="3" level="6" cost="31" name="Power Strike" min_level="10"/>
			<skill id="16" level="4" cost="31" name="Mortal Blow" min_level="10"/>
			<skill id="16" level="5" cost="31" name="Mortal Blow" min_level="10"/>
			<skill id="16" level="6" cost="31" name="Mortal Blow" min_level="10"/>
			<skill id="142" level="4" cost="140" name="Armor Mastery" min_level="15"/>
			<skill id="142" level="5" cost="140" name="Armor Mastery" min_level="15"/>
			<skill id="141" level="3" cost="290" name="Weapon Mastery" min_level="15"/>
			<skill id="70" level="1" cost="140" name="Drain Health" min_level="15"/>
			<skill id="70" level="2" cost="140" name="Drain Health" min_level="15"/>
			<skill id="56" level="7" cost="95" name="Power Shot" min_level="15"/>
			<skill id="56" level="8" cost="95" name="Power Shot" min_level="15"/>
			<skill id="56" level="9" cost="95" name="Power Shot" min_level="15"/>
			<skill id="3" level="7" cost="95" name="Power Strike" min_level="15"/>
			<skill id="3" level="8" cost="95" name="Power Strike" min_level="15"/>
			<skill id="3" level="9" cost="95" name="Power Strike" min_level="15"/>
			<skill id="294" level="1" cost="290" name="Shadow Sense" min_level="15"/>
			<skill id="16" level="7" cost="95" name="Mortal Blow" min_level="15"/>
			<skill id="16" level="8" cost="95" name="Mortal Blow" min_level="15"/>
			<skill id="16" level="9" cost="95" name="Mortal Blow" min_level="15"/>
			<!--HARDCODED: <skill id="239"level="1" name="Expertise D" min_level="20"/>-->
			<skill id="1320" level="2" name="Create Common Item" min_level="20"/>
			<skill id="1320" level="3" name="Create Common Item" min_level="28"/>
			<skill id="1320" level="4" name="Create Common Item" min_level="36"/>
			<!--HARDCODED: <skill id="239"level="2" name="Expertise C" min_level="40"/>-->
			<skill id="1320" level="5" name="Create Common Item" min_level="43"/>
			<skill id="1320" level="6" name="Create Common Item" min_level="49"/>
			<!--HARDCODED: <skill id="239"level="3" name="Expertise B" min_level="52"/>-->
			<skill id="1320" level="7" name="Create Common Item" min_level="55"/>
			<!--HARDCODED: <skill id="239"level="4" name="Expertise A" min_level="61"/>-->
			<skill id="1320" level="8" name="Create Common Item" min_level="62"/>
			<skill id="1320" level="9" name="Create Common Item" min_level="70"/>
			<!--HARDCODED: <skill id="239"level="5" name="Expertise S" min_level="76"/>-->
			<!--HARDCODED: <skill id="239"level="6" name="Expertise S80" min_level="80"/>-->
			<!--HARDCODED: <skill id="239"level="8" name="Expertise R" min_level="85"/>-->
			<!--HARDCODED: <skill id="239"level="9" name="Expertise R95" min_level="95"/>-->
			<!--HARDCODED: <skill id="239"level="10" name="Expertise R99" min_level="99"/>-->
		</class>
	</normal_skill_tree>
</list>

=== NacheGod/ertheia/dist/gameserver/data/skill_tree/normal_skill_tree/[25] elven_mage.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "tree.dtd">
<!--Create by VISTALL. Full reworked to Glory of Destruction by Bonux. -->
<list>
	<normal_skill_tree>
		<class id="25"> <!--elven_mage-->
			<skill id="194" level="1" name="Lucky" min_level="1"/>
			<skill id="214" level="1" name="Mana Recovery" min_level="1"/>
			<skill id="118" level="1" name="Magician's Movement" min_level="1"/>
			<skill id="163" level="1" name="Spellcraft" min_level="1"/>
			<skill id="1322" level="1" name="Common Craft" min_level="1"/>
			<skill id="1216" level="1" name="Self Heal" min_level="1"/>
			<skill id="1177" level="1" name="Wind Strike" min_level="1"/>
			<skill id="1320" level="1" name="Create Common Item" min_level="5"/>
			<skill id="146" level="1" cost="26" name="Anti Magic" min_level="7"/>
			<skill id="146" level="2" cost="26" name="Anti Magic" min_level="7"/>
			<skill id="244" level="1" cost="52" name="Armor Mastery" min_level="7"/>
			<skill id="249" level="1" cost="52" name="Weapon Mastery" min_level="7"/>
			<skill id="1012" level="1" cost="52" name="Cure Poison" min_level="7"/>
			<skill id="1184" level="1" cost="26" name="Ice Bolt" min_level="7"/>
			<skill id="1184" level="2" cost="26" name="Ice Bolt" min_level="7"/>
			<skill id="1011" level="1" cost="17" name="Heal" min_level="7"/>
			<skill id="1011" level="2" cost="17" name="Heal" min_level="7"/>
			<skill id="1011" level="3" cost="17" name="Heal" min_level="7"/>
			<skill id="1068" level="1" cost="52" name="Might" min_level="7"/>
			<skill id="1177" level="2" cost="26" name="Wind Strike" min_level="7"/>
			<skill id="1177" level="3" cost="26" name="Wind Strike" min_level="7"/>
			<skill id="1040" level="1" cost="52" name="Shield" min_level="7"/>
			<skill id="146" level="3" cost="110" name="Anti Magic" min_level="14"/>
			<skill id="146" level="4" cost="110" name="Anti Magic" min_level="14"/>
			<skill id="1015" level="1" cost="70" name="Battle Heal" min_level="14"/>
			<skill id="1015" level="2" cost="70" name="Battle Heal" min_level="14"/>
			<skill id="1015" level="3" cost="70" name="Battle Heal" min_level="14"/>
			<skill id="244" level="2" cost="110" name="Armor Mastery" min_level="14"/>
			<skill id="244" level="3" cost="110" name="Armor Mastery" min_level="14"/>
			<skill id="249" level="2" cost="210" name="Weapon Mastery" min_level="14"/>
			<skill id="1027" level="1" cost="70" name="Group Heal" min_level="14"/>
			<skill id="1027" level="2" cost="70" name="Group Heal" min_level="14"/>
			<skill id="1027" level="3" cost="70" name="Group Heal" min_level="14"/>
			<skill id="1184" level="3" cost="110" name="Ice Bolt" min_level="14"/>
			<skill id="1184" level="4" cost="110" name="Ice Bolt" min_level="14"/>
			<skill id="1011" level="4" cost="70" name="Heal" min_level="14"/>
			<skill id="1011" level="5" cost="70" name="Heal" min_level="14"/>
			<skill id="1011" level="6" cost="70" name="Heal" min_level="14"/>
			<skill id="1206" level="1" cost="210" name="Wind Shackle" min_level="14"/>
			<skill id="1164" level="1" cost="210" name="Curse: Weakness" min_level="14"/>
			<skill id="1177" level="4" cost="110" name="Wind Strike" min_level="14"/>
			<skill id="1177" level="5" cost="110" name="Wind Strike" min_level="14"/>
			<!--HARDCODED: <skill id="239"level="1" name="Expertise D" min_level="20"/>-->
			<skill id="1320" level="2" name="Create Common Item" min_level="20"/>
			<skill id="1320" level="3" name="Create Common Item" min_level="28"/>
			<skill id="1320" level="4" name="Create Common Item" min_level="36"/>
			<!--HARDCODED: <skill id="239"level="2" name="Expertise C" min_level="40"/>-->
			<skill id="1320" level="5" name="Create Common Item" min_level="43"/>
			<skill id="1320" level="6" name="Create Common Item" min_level="49"/>
			<!--HARDCODED: <skill id="239"level="3" name="Expertise B" min_level="52"/>-->
			<skill id="1320" level="7" name="Create Common Item" min_level="55"/>
			<!--HARDCODED: <skill id="239"level="4" name="Expertise A" min_level="61"/>-->
			<skill id="1320" level="8" name="Create Common Item" min_level="62"/>
			<skill id="1320" level="9" name="Create Common Item" min_level="70"/>
			<!--HARDCODED: <skill id="239"level="5" name="Expertise S" min_level="76"/>-->
			<!--HARDCODED: <skill id="239"level="6" name="Expertise S80" min_level="80"/>-->
			<!--HARDCODED: <skill id="239"level="8" name="Expertise R" min_level="85"/>-->
			<!--HARDCODED: <skill id="239"level="9" name="Expertise R95" min_level="95"/>-->
			<!--HARDCODED: <skill id="239"level="10" name="Expertise R99" min_level="99"/>-->
		</class>
	</normal_skill_tree>
</list>
